### ISSUE TITLE
userの`item_count`について

### ISSUE THREAD

**Issue by Cj-bc** [mattn/qiita-vim#3]
連投申し訳無いです。
元のコードでは、こういった記述がありました。
https://github.com/mattn/qiita-vim/blob/73235dc95a7b12b862112eddd059efe3b25380d3/autoload/qiita.vim#L83

`item_count`に`item`を直接入れているようですが、これは*投稿の数*を代入するので良いですか...?
v2の方ではもともと`item_count`が返されるので、現状はそれをそのまま代入しています。
ただ元の挙動と異なる可能性があるため、聞きました(今の所正常に動いています)
特に意味がないようであれば現状のままにしようと思っています。

**Comment by mattn** [comment]
たぶん僕のミスですね。

**Comment by Cj-bc** [comment]
わかりました、ありがとうございます
